language: python
python:
- 3.6
env:
- PKG_NAME=chiscore
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: qCmX7PjIEYh1Hg2Ruh4eahcuFOtixOUDREmY55xb7EhTsxP9q8qzJdGbsMYwcKBCbIO2+DSErenRpLUWonVfhWli6Colf2hSlU+MkChid6P+cYvLbL/seegMkZhwzUgpvoTY37AceQnvrbwvNOFxOnpKxi50DSyzTogfsP7tIrnB/E9J3uCPPO53/5aCfjZc105x3FKB1kiAfyvHLLOQShaNE0Exz9sxE66oEba72aIMGU6xvhGEVVgVHSF7JcTtnNQ0EcH6wsiw/lm/jlk332vp4cWZqxYVDzmSMoqZXOqIQ0MPFG8h/XwwllUFh+KNRnapVhvoDp47foa/jnYroPJGzGfSOm1prkz+Ere9b3b4K3JZvSK+ZYFqiAw+NhdnCh3B0sGlNJtKTIBX/MtrnQ1QMoZKIUBwV/aLwm6NDyKTlfLPZzU8kB67CmwQDuVs6T97Xks7P2lcBuzRwpLA447XoPk/VsUh7R41vqmBWR3BZuz1zdT8E7UHhST/Mu/qKx5AvwxlEBP+D9siNv27jyhnfnMd2HbW9/S9PhpmxvC0OrPVilkb8P6swvsg5ws22nGoQWMQ+iHS39vdjEa+kNOrK55e7U++4s50gDNebkmALcYfED1E1GvjdPQ7nM3J6EIzQKFRhHVRoZl4+Csb0c/GmJpEKTN8a0Gahx6+9M4=
  on:
    tags: true
    repo: limix/chiscore
    branch: master
