language: python
python:
- 3.6
env:
- PKG_NAME=chiscore
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: BVs0jGwk2MF5Rf4RW0kFJjGJXxlJYpnX48Sb2ThkLUujCLBZNx0mpOy1qEy9Alt2JZLMht8G+wMcqkVYBQd/Qew2+6dcU3FbNQzLA6bxlwO+sbynG5EyCANKSATAaM9z4QVFHBln4IrTZCaHQYeQymYrOak7TcFo54MK/I+yZBcrueVjYbJdeFMYIw4+DfdMbormjuocQcJP9uspLO13RrnpK7g5vj5D+n2XTu3Alf9sFjLS6/+nspsHGgOFyElW2F0VCQnwewT9uuZEFEY9nbaoBeoZsBO0NhAFa4AZayvxEnSaJGeaAAw46x1tO9jcJwn0jMzWMDMPFD8U6KFGl4uu6wNeI1aA8zEW4XTEfds6U6FfKvCaGRs04Xiw+vX6vLbosjT5PpnR+/5bxvu3MgirrB5HNq6gTJOwjcHHlZ2t1TEsspTAfIJxKcjM4BXjSDWcnNXTJp+8FogguIE3/VSchSpeluWl387dTSV/RF4zOOLXQEqZpIZ7lLRLTAbeW0IK0tZWNOxT6MXDPFOMMHE+UsHs0sFAO741K/S3BbW+M9xKhT2zLrZKU0xute/W854usmkAsTfTJ+gsPLlWah7UorrmmxPPOez5HwyG81ZUX+R50u6+VE2wllLHJQx1C9J8AX/hw4sGCM4jnwIOcaJsBBA5Nhmj4QDG6zLD2So=
  on:
    tags: true
    repo: limix/chiscore
