language: python
python:
- 3.6
env:
- PKG_NAME=glimix_core
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: lf2EXbgNYVewF+wUxA2M0Vfoe902bYOkV0wrDtDOB6UXQIwGW0ZEtl2X9i69e6PXfYBYt8KHNISD7peYFr7/tvT6B64WqyOv5ONEuVACDsy1MGSLAxYnCXTiHQeBzE72IwijbW1sKajcJssj8R/lUPHXgS6Cqm1sJVGLcDCFfj0Q2wWt0whk8Atp9meS90K3ary80vIal79H+iZ8mAS7aj6Za2TIT2p9zo4eOzfeU3U81BEfQ9m1rgXqHKgPnHQ+uLcTdbHsVu2aoGZDKa6NKwgw8yBXnSNCMhKFC2noGq3ziHEf84JvICCLgRk4a8T3CfF3x6U+zu8iNLSFeV2D8Zg4pLp1LxF2RWOR6pblsuf2s/YLuxqCnhO6m5ENit45wjYul5sjnrvf8wHdYyr+4EpxesgINrp8GkuMTwPEVdRrpjFnX6qep3UK+9e7qRwbwG1zkAg3hqQoAnapop9YcItux5Y8K6HIifV7Z4NX0BJGsGCwfpzSyq0D4NZjL8OFTXL+V7kZQd2bb2283BI4vULn7jNUhf2lMV7XODwd4f6rcXvFuGc+vn+gJ5XQ5MskQeOawYk45m/IULqIsK3Baf6S06E9vilmnM9IDFbcylw7BoKjOH4/KoMdiy8jAaAbRH6OHM9B2klkfvgmkVqO9Uc5blElMTeFE5jm0aenir8=
  on:
    tags: true
    repo: limix/glimix-core
    branch: master
    python: 3.6
