language: python
python: 3.6
matrix:
  include:
    - sudo: required
    - os: osx
      language: generic
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew unlink python2
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3
        - export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
        - ln -s $(brew --prefix)/bin/python3 $(brew --prefix)/bin/python
        - ln -s $(brew --prefix)/bin/pip3 $(brew --prefix)/bin/pip
        - hash -r
        - python --version
        - python -m pip install --upgrade pip setuptools wheel
env:
- PKG_NAME=chiscore
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: Fl3hvaSLttsK2Y9eZiX7HFC7LNHi63Mfti1p0GDFXlLqzt2Q25nnzMZ8R3cwPkLCe/SztJGIlbGZB/79TlGmXKEs6ifPzarPfBFOXcY+vvrB53h2WQXtraJioEgqMZt+oVyOZ2Gvynubk4E8dgycvdSGL33NXOJMWYr5wsbhvZNeQshW9bDqrl8+XF5hb0pT9oMAVIir73sYpIvDZd51F7SHC0FEkjRVkHB9xPrFFTckp5K0s9VMAkVzvC0z6Q+kIiVTQ4ForFhfSiBgizkDj1hq3rNRUiBVGIqIbd6F246hAmo2QAWt2cLmmeWLD54gRmzFiHgix6riwvuvkCb4HrTLHt+h0rHuuMHPOey0W7pji1NZ71FRxcJaIEqehzefUIXyvF2HVlUje4LoRGHNaNlXtxNw+r4It+LnZzmuqP3I+dgoF8UE8PjK1SUrVtMHovq1ura1FHSVUQshMIXz+F5WF/NWmrsQYGSQ9T+RQxwGctXbCkIfYV1Ajt/CgUdYT4jJUyw8j20svZdy/tfDTNciYsEwZ+ZQ4mFN7U0oYh2E3E8OlyW1HZMmqA2auwLZvQ3pM9WjfuN2rhgvd7PkwCKuzvd8c6enFVB/pBUHmJLszaNL40n9ZjiJcz7VafETdsLluBMceIQdWoG5sIlzLU9pbbO+d4rQjDS/9SSAqhM=
  on:
    tags: true
    repo: limix/chiscore
    branch: master
    python: 3.6
