language: python
python:
- 3.6
env:
- PKG_NAME=chiscore
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: m0UbEoEJSlr1xyiTT2ZzRcpyw9xyIqyTrXQ2MCYcbMRfqncrhHMtAGgeNM/qJ0lmhpTG2482GCQ6bTcILokyrXnt3Q6CJZdu/dakzjnhV5pdKoGDfBWDE9v72getpI4PHAD91Asx9+qDc4cl/7BkcKy0yLS0Yr7MgnEjevSKEsajVv3jsut0U8LyHo/GKs8S8nR87Dy+0z1LXSAC+Xp2OYHDWkWLbpZdBwhE36FKBwZIEK8T9W3QSvxWydFNFdqx0pIRxJjAiQGeeuWwPJI0bt5LmV0NkDLDRAOLim/Sj8j/TBHwn1GhamgUw/indShuYriN8mIgg2m9x4ONnc8nFeFXrRPInf1/9hGZOsdHhxuTmeQdRiVfMLxDaEOGm2IcEzWL8tqqtp5wE/cnUO++tjzCC1b9dPhverMyRKyRXJj3A2Ejv94oUV3wYSBd+UWX1kwNl19soQTfUe3AFJjiIknUEota+4UABfB4OaMg+N08fRGJAZsqMflR/a635a7uDm1/HPBFtBmsn5nvFluBXtvcnqpJF/jaeNWD1pt7vjFOiGYdCBNfPTi6IYxIYAy2bCIjt+eLrx4q4W+nPRJY2gerd3IfVhoOc8NZzfmKtsBfPlKeRz79oeFMO4DCfISR7CrmtovLbjMMFoLM5NwsoY9nR97U4zg9FvbUYW2gCj8=
  on:
    tags: true
    repo: limix/chiscore
    branch: master